//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using System.Collections.Generic;

namespace CsvModule
{
    /// <summary>
    /// CSV 文件的存储地址
    /// </summary>
    public class Csv
    {
     private CsvLoader loader = new CsvLoader();
     public static Dictionary<int, ItemCfg> ItemCfgStore;
     public void Init()
     {
        ItemCfgStore = loader.Load<ItemCfg>(CsvName.ItemCfg);
     }
#if UNITY_EDITOR
     public void InitInEditor()
     {
        ItemCfgStore = loader.Load<ItemCfg>(CsvName.ItemCfg);
     }
#endif
  }
}
