//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using System.Collections.Generic;

    /// <summary>
    /// CSV 文件的存储地址
    /// </summary>
    public class Csv
    {
     private CsvLoader loader = new CsvLoader();
     public static Dictionary<int, InteractionCfg> InteractionCfgStore;
     public static Dictionary<int, ItemCfg> ItemCfgStore;
     public static Dictionary<int, LocalizationGameplayCfg> LocalizationGameplayCfgStore;
     public static Dictionary<int, LocalizationUICfg> LocalizationUICfgStore;
     public void Init()
     {
        InteractionCfgStore = loader.Load<InteractionCfg>(CsvName.InteractionCfg);
        ItemCfgStore = loader.Load<ItemCfg>(CsvName.ItemCfg);
        LocalizationGameplayCfgStore = loader.Load<LocalizationGameplayCfg>(CsvName.LocalizationGameplayCfg);
        LocalizationUICfgStore = loader.Load<LocalizationUICfg>(CsvName.LocalizationUICfg);
     }
#if UNITY_EDITOR
     public void InitInEditor()
     {
        InteractionCfgStore = loader.Load<InteractionCfg>(CsvName.InteractionCfg);
        ItemCfgStore = loader.Load<ItemCfg>(CsvName.ItemCfg);
        LocalizationGameplayCfgStore = loader.Load<LocalizationGameplayCfg>(CsvName.LocalizationGameplayCfg);
        LocalizationUICfgStore = loader.Load<LocalizationUICfg>(CsvName.LocalizationUICfg);
     }
#endif
}
