//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateCsvName
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

    /// <summary>
    /// CSV 文件的存储地址
    /// </summary>
    public class CsvName
    {
        public const string InteractionCfg = "InteractionCfg";
        public const string ItemCfg = "ItemCfg";
        public const string LocalizationGameplayCfg = "LocalizationGameplayCfg";
        public const string LocalizationUICfg = "LocalizationUICfg";
}