//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateCsvName
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CsvModule
{
    /// <summary>
    /// CSV 文件的存储地址
    /// </summary>
    public class CsvName
    {
        public const string ItemCfg = "ItemCfg";
    }
}