//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateCsvStore
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CsvModule
{
    /// <summary>
    /// CSV 文件的存储地址
    /// </summary>
    public class CsvStore
    {
    public static readonly Dictionary<string, string[,]> store = new Dictionary<string, string[,]>()
     {
             {CsvName.ItemCfg, ItemCfg.properties},
        };
     }
}
