//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateClassFromCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using UnityEngine;
public class ItemCfg:CsvBase
{
    public int id { get; set; }
    public int target { get; set; }
    public int result { get; set; }
    public string name { get; set; }
    public string sprite { get; set; }
    public string comment { get; set; }
   public static readonly string[,] properties = 
   {
       {"1000","0","0","0","0","key",},
       {"1001","0","0","0","0","ticket",},
   };
}
