//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateClassFromCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using UnityEngine;
public class LocalizationUICfg:CsvBase
{
    public int id { get; set; }
    public string ch { get; set; }
    public string en { get; set; }
   public static readonly string[,] properties = 
   {
       {"1010000","新游戏","New Game",},
       {"1010001","继续","Continue",},
       {"1010002","退出","Quit",},
       {"1010003","关于我们","About Us",},
   };
}
