//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateClassFromCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using UnityEngine;
public class LocalizationUICfg:CsvBase
{
    public int id { get; set; }
    public string ch { get; set; }
    public string en { get; set; }
   public static readonly string[,] properties = 
   {
       {"Menu_NewGame","0","New Game",},
       {"Menu_Continue","0","0",},
       {"Menu_Quit","0","0",},
       {"Menu_AboutUs","0","0",},
   };
}
