//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated
//     via CsvGenerator.GenerateClassFromCsv
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Core.Csv;
using UnityEngine;
public class LocalizationGameplayCfg:CsvBase
{
    public int id { get; set; }
    public string ch { get; set; }
    public string en { get; set; }
   public static readonly string[,] properties = 
   {
       {"2010000","xxxx","xxxxx",},
   };
}
