using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Core.Csv;
using Core.Editor;
using Core.Logger;
using UnityEditor;
using UnityEngine;


public class CsvGenerator : Editor
{
    private static readonly string filePath = "./csv";
    private static string pathGenerated = $"{Application.dataPath}/Scripts/Repo/#Generated/CSV";

    [MenuItem("Csv/Generate Csv")]
    private static void Generate()
    {
        // 创建，清空 生成目标文件夹
        if (System.IO.Directory.Exists(pathGenerated))
            System.IO.Directory.Delete(pathGenerated, true);
        System.IO.Directory.CreateDirectory(pathGenerated);
        ReadAllCsv(filePath);
    }

    private static void ReadAllCsv(string path)
    {
        try
        {
            string[] csvFiles = Directory.GetFiles(path, "*.csv", SearchOption.AllDirectories);
            foreach (var file in csvFiles)
            {
                ReadCsv(file);
            }

            GenerateCsvName(csvFiles);
            GenerateCsvStore(csvFiles);
            GenerateCsv(csvFiles);
        }
        catch (Exception e)
        {
            Debug.Log("Error in Read Csv" + e.Message);
            throw;
        }
    }

    private static void ReadCsv(string path)
    {
        try
        {
            if (!File.Exists(path))
            {
                Debug.LogError("There is no such file: " + path);
                return;
            }

            using (StreamReader reader = new StreamReader(path, Encoding.UTF8))
            {
                string headerLine = reader.ReadLine();
                if (headerLine != null)
                {
                    string[] propers = headerLine.Split(',');
                    var fieldTypes = new string[propers.Length];
                    var headers = new string[propers.Length];
                    for (int i = 0; i < propers.Length; i++)
                    {
                        var temp = propers[i].Split("&");
                        headers[i] = temp[0];
                        if (temp[0] == "id")
                        {
                            fieldTypes[i] = "int";
                        }
                        else
                        {
                            fieldTypes[i] = temp[1];
                        }
                    }

                    var lines = new List<string>();
                    while (reader.ReadLine() is { } line)
                    {
                        lines.Add(line);
                        /*string[] fields = line.Split(',');
                        for (int i = 0; i < fields.Length; i++)
                        {
                            var info = fields[i].Split("&");

                            if (int.TryParse(fields[i], out _))
                            {
                                fieldTypes[i] = "int";
                            }
                            else if (float.TryParse(fields[i], out _))
                            {
                                fieldTypes[i] = "float";
                            }
                            else if (long.TryParse(fields[i], out _))
                            {
                                fieldTypes[i] = "long";
                            }
                            else
                            {
                                fieldTypes[i] = "string";
                            }
                        }*/
                    }

                    GenerateClassFromCsv(path, headers, fieldTypes, lines);
                }
            }
        }
        catch (Exception e)
        {
            GameLogger.Error("Read csv line error: " + path);
            GameLogger.Error("{0}", e);
        }
    }

    private static void GenerateClassFromCsv(string path, string[] headers, string[] fieldTypes, List<string> lines)
    {
        // 处理文件名作为类名
        string fileName = Path.GetFileNameWithoutExtension(path);
        string className = fileName.Replace("\\", "").Replace("/", "");

        // 使用 StringBuilder 生成类的字符串
        StringBuilder classBuilder = new StringBuilder();
        classBuilder.AppendLine(
            EditorUtils.FormatAutoGeneratedSummary($"{nameof(CsvGenerator)}.{nameof(GenerateClassFromCsv)}"));
        classBuilder.AppendLine("using Core.Csv;");
        classBuilder.AppendLine("using UnityEngine;");
        classBuilder.AppendLine("public class " + className + ":" + nameof(CsvBase));
        classBuilder.AppendLine("{");

        for (int i = 0; i < headers.Length; i++)
        {
            classBuilder.AppendLine("    public " + fieldTypes[i] + " " + headers[i] + " { get; set; }");
        }

        classBuilder.AppendLine("   public static readonly string[,] properties = ");
        classBuilder.AppendLine("   {");

        for (int i = 0, count = lines.Count; i < count; ++i)
        {
            var fields = lines[i].Split(",");
            classBuilder.Append("       {");
            foreach (var t in fields)
            {
                if (t.Equals(string.Empty))
                {
                    classBuilder.Append("\"0\"");
                }
                else
                {
                    classBuilder.Append($"\"{t}\"");
                }

                classBuilder.Append(",");
            }

            classBuilder.Append("}");
            classBuilder.AppendLine(",");
        }

        classBuilder.AppendLine("   };");

        classBuilder.AppendLine("}");

        // 输出生成的类字符串
        string classString = classBuilder.ToString();

        // 保存生成的类到文件（可选）
        string outputPath = Path.Combine(pathGenerated, className + ".cs");
        File.WriteAllText(outputPath, classString);
        Debug.Log("Class saved to: " + outputPath);
    }

    private static void GenerateCsvName(string[] files)
    {
        var sb = new StringBuilder();

        sb.AppendLine(EditorUtils.FormatAutoGeneratedSummary($"{nameof(CsvGenerator)}.{nameof(GenerateCsvName)}"));
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// CSV 文件的存储地址");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public class CsvName");
        sb.AppendLine("    {");
        foreach (var file in files)
        {
            // 字段名首字母大写
            var directoryName = System.IO.Path.GetDirectoryName(file)?
                .Replace("\\", "/")
                .Replace("./csv", "").Replace("/", "");
            var fileName = System.IO.Path.GetFileNameWithoutExtension(file).Replace("\\", "/")
                .Replace("./csv/", "");
            var fieldName = fileName.Substring(0, 1).ToUpper() + fileName.Substring(1);
            if (string.IsNullOrEmpty(directoryName))

                sb.AppendLine($"        public const string {fieldName} = \"{fileName}\";");
            else
                sb.AppendLine($"        public const string {fieldName} = \"{directoryName}/{fileName}\";");
        }
        sb.Append("}");

        var path = System.IO.Path.Combine(pathGenerated, "CsvName.cs");
        System.IO.File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }

    private static void GenerateCsvStore(string[] files)
    {
        var sb = new StringBuilder();

        sb.AppendLine(EditorUtils.FormatAutoGeneratedSummary($"{nameof(CsvGenerator)}.{nameof(GenerateCsvStore)}"));
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// CSV 文件的存储地址");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public class CsvStore");
        sb.AppendLine("    {");
        sb.AppendLine(
            $"    public static readonly Dictionary<string, string[,]> store = new Dictionary<string, string[,]>()");
        sb.AppendLine("     {");
        foreach (var file in files)
        {
            // 字段名首字母大写
            var directoryName = System.IO.Path.GetDirectoryName(file)?
                .Replace("\\", "/")
                .Replace("./csv", "").Replace("/", "");
            var fileName = System.IO.Path.GetFileNameWithoutExtension(file).Replace("\\", "/")
                .Replace("./csv/", "");
            var fieldName = fileName.Substring(0, 1).ToUpper() + fileName.Substring(1);


            sb.AppendLine("             {" + $"CsvName.{fileName}, {fileName}.properties" + "},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("}");
        var path = System.IO.Path.Combine(pathGenerated, "CsvStore.cs");
        System.IO.File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }

    private static void GenerateCsv(string[] files)
    {
        var sb = new StringBuilder();

        sb.AppendLine(EditorUtils.FormatAutoGeneratedSummary($"{nameof(CsvGenerator)}.{nameof(GenerateCsv)}"));
        sb.AppendLine("using Core.Csv;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// CSV 文件的存储地址");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public class Csv");
        sb.AppendLine("    {");
        sb.AppendLine($"     private CsvLoader loader = new CsvLoader();");
        foreach (var file in files)
        {
            var fileName = System.IO.Path.GetFileNameWithoutExtension(file).Replace("\\", "/")
                .Replace("./csv/", "");
            sb.AppendLine($"     public static Dictionary<int, {fileName}> {fileName}Store;");
        }

        // Runtime
        sb.AppendLine("     public void Init()");
        sb.AppendLine("     {");
        foreach (var file in files)
        {
            var fileName = System.IO.Path.GetFileNameWithoutExtension(file).Replace("\\", "/")
                .Replace("./csv/", "");
            sb.AppendLine($"        {fileName}Store = loader.Load<{fileName}>(CsvName.{fileName});");
        }

        sb.AppendLine("     }");

        //Editor
        sb.AppendLine("#if UNITY_EDITOR");
        sb.AppendLine("     public void InitInEditor()");
        sb.AppendLine("     {");
        foreach (var file in files)
        {
            var fileName = System.IO.Path.GetFileNameWithoutExtension(file).Replace("\\", "/")
                .Replace("./csv/", "");
            sb.AppendLine($"        {fileName}Store = loader.Load<{fileName}>(CsvName.{fileName});");
        }

        sb.AppendLine("     }");
        sb.AppendLine("#endif");
        sb.AppendLine("}");
        var path = System.IO.Path.Combine(pathGenerated, "Csv.cs");
        System.IO.File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }
}