namespace Core.Editors
{
﻿public static class EditorUtils
    {
#region 自动生成的代码，文件开头的注释模板
        /// <summary>
        /// 自动生成的代码，文件开头的注释模板
        /// </summary>
        public static string FormatAutoGeneratedSummary (string generator)
        {
            var sb = new System.Text.StringBuilder ();
            sb.AppendLine ("//------------------------------------------------------------------------------");
            sb.AppendLine ("// <auto-generated>");
            sb.AppendLine ("//     This code was generated");
            sb.AppendLine ($"//     via {generator}");
            sb.AppendLine ("//");
            sb.AppendLine ("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine ("//     the code is regenerated.");
            sb.AppendLine ("// </auto-generated>");
            sb.Append ("//------------------------------------------------------------------------------");
            return sb.ToString ();
        }
#endregion
    }
}